# Generated by Django 5.0.6 on 2024-09-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshop',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Precio Venta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carshop',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Precio Unitario'),
            preserve_default=False,
        ),
    ]
