# Generated by Django 5.0.6 on 2024-09-25 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
        ('venta', '0002_carshop_sale_price_carshop_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='anulate',
            new_name='anulado',
        ),
        migrations.RenameField(
            model_name='saledetail',
            old_name='anulate',
            new_name='anulado',
        ),
        migrations.RemoveField(
            model_name='saledetail',
            name='purchase_price',
        ),
        migrations.AddField(
            model_name='sale',
            name='cliente',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='proveedor.proveedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='condicion_pago',
            field=models.CharField(choices=[('1', 'CONTADO'), ('2', 'CREDITO')], default=1, max_length=1, verbose_name='Estado de Pago'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='correlativo',
            field=models.CharField(default=1, max_length=12, verbose_name='Correlativo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='sale',
            name='igv',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='IGV'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='serie',
            field=models.CharField(default=1, max_length=4, verbose_name='Serie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saledetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Valor Unitario'),
            preserve_default=False,
        ),
    ]
