# Generated by Django 5.0.6 on 2024-09-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_rename_anulate_sale_anulado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Ganancia'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='condicion_pago',
            field=models.CharField(choices=[('1', 'Contado'), ('2', 'Crédito')], max_length=1, verbose_name='Estado de Pago'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='type_payment',
            field=models.CharField(choices=[('1', 'Efectivo'), ('2', 'VISA'), ('3', 'MasterCard'), ('4', 'American Express'), ('5', 'Diners Club'), ('6', 'Cheque'), ('7', 'Depósito o Transferencia'), ('8', 'Yape'), ('9', 'Niubiz'), ('10', 'Izipay'), ('11', 'Vendemas'), ('12', 'Plin')], max_length=2, verbose_name='TIPO PAGO'),
        ),
    ]
