# Generated by Django 5.0.6 on 2024-09-30 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_remove_cliente_contacto_alter_cliente_direccion_and_more'),
        ('venta', '0004_saledetail_profit_alter_sale_condicion_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='cliente.cliente'),
        ),
    ]
