# Generated by Django 5.0.6 on 2024-10-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_alter_sale_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitario'),
        ),
    ]
