# Generated by Django 5.0.6 on 2024-09-17 05:18

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '__first__'),
        ('proveedor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('barcode', models.CharField(max_length=13, unique=True)),
                ('count', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_car_compra', to='producto.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'Carrito de compras',
                'verbose_name_plural': 'Carrito de compras',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tipo_documento', models.CharField(choices=[('00', 'Sin Comprobante'), ('01', 'Factura'), ('03', 'Boleta'), ('07', 'Nota de Credito'), ('08', 'Nota de Debito')], max_length=2, verbose_name='Tipo de Documento')),
                ('serie', models.CharField(max_length=4, verbose_name='Serie')),
                ('correlativo', models.CharField(max_length=12, verbose_name='Correlativo')),
                ('forma_pago', models.CharField(choices=[('01', 'Efectivo'), ('02', 'VISA'), ('03', 'MasterCard'), ('04', 'American Express'), ('05', 'Diners Club'), ('06', 'Cheque'), ('07', 'Depósito o Transferencia'), ('08', 'Yape'), ('09', 'Niubiz'), ('10', 'Izipay'), ('11', 'Vendemas'), ('12', 'Plin')], max_length=2, verbose_name='Forma de Pago')),
                ('estado_pago', models.CharField(choices=[('1', 'CONTADO'), ('2', 'CREDITO')], max_length=1, verbose_name='Estado de Pago')),
                ('fecha_compra', models.DateField(verbose_name='Fecha de Compra')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('igv', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IGV')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('anulado', models.BooleanField(default=False, verbose_name='Anulado')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('count', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='producto.producto')),
                ('compra_cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compra.purchase')),
            ],
            options={
                'verbose_name': 'Compra Detalle',
                'verbose_name_plural': 'Compras Detalles',
            },
        ),
    ]
