# Generated by Django 5.0.6 on 2024-09-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='estado_pago',
            new_name='condicion_pago',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='forma_pago',
        ),
        migrations.AddField(
            model_name='purchase',
            name='medio_pago',
            field=models.CharField(choices=[('1', 'Efectivo'), ('2', 'VISA'), ('3', 'MasterCard'), ('4', 'American Express'), ('5', 'Diners Club'), ('6', 'Cheque'), ('7', 'Depósito o Transferencia'), ('8', 'Yape'), ('9', 'Niubiz'), ('10', 'Izipay'), ('11', 'Vendemas'), ('12', 'Plin')], default='1', max_length=2, verbose_name='Forma de Pago'),
            preserve_default=False,
        ),
    ]
