# Generated by Django 5.0.6 on 2024-09-18 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_rename_estado_pago_purchase_condicion_pago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='tipo_documento',
            new_name='tipo_comprobante',
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='user_compra', to=settings.AUTH_USER_MODEL, verbose_name='cajero'),
            preserve_default=False,
        ),
    ]
