# Generated by Django 5.0.6 on 2024-09-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_rename_tipo_documento_purchase_tipo_comprobante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cantidad',
            field=models.PositiveIntegerField(default='1', verbose_name='Cantidad de Productos'),
            preserve_default=False,
        ),
    ]
