# Generated by Django 5.0.6 on 2024-09-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_purchase_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshop',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Costo'),
            preserve_default=False,
        ),
    ]
