# Generated by Django 5.0.6 on 2024-09-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0005_carshop_product_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carshop',
            old_name='product_cost',
            new_name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='total',
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Impuesto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Precio Unitario'),
            preserve_default=False,
        ),
    ]
