# Generated by Django 5.0.6 on 2024-09-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0006_rename_product_cost_carshop_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshop',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Precio Unitario'),
            preserve_default=False,
        ),
    ]
