# Generated by Django 5.0.6 on 2024-09-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='num_purchase',
            field=models.PositiveIntegerField(default=0, verbose_name='numero de compras'),
        ),
    ]
